---
kind: pipeline
type: docker
name: default
trigger:
  branch: 
  - master

steps:
- name: submodules
  image: alpine/git
  commands:
  - git submodule update --init --recursive
  
- name: Version Check
  image: jguyomard/hugo-builder
  commands:
  - echo "Checking hugo version"
  - hugo version

- name: Build 
  image: jguyomard/hugo-builder
  commands:
  - hugo --destination /drone/src/build
  - minify -r -o /drone/src/build /drone/src/build

- name: Upload 
  image: jguyomard/hugo-builder
  commands:
  - eval `ssh-agent -s`
  - echo "$SSH_KEY" | ssh-add -
  - mkdir -p ~/.ssh
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  - rsync -rv -e "ssh -p 22" /drone/src/build/ drone@niklasarnitz.com:/opt/services-docker/data/nginx/var/www/niklasarnitz.com/ --checksum
  environment:
    SSH_KEY:
      from_secret: drone_ssh_key
