baseurl = "//niklasarnitz.codes"
title = "Niklas Arnitz"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
    author = "Niklas Arnitz"
    info = "Software Engineer & Developer"
    description = "Niklas Arnitz' portfolio"
    keywords = "developer,personal,portfolio,ios,macos,swift,developer"
    avatarurl = "images/avatar.jpg"

    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"

    footercontent = "©Niklas Arnitz 2019"

    hidecredits = false
    hidecopyright = true

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/niklasarnitz/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 2
    url = "https://twitter.com/niklas_arnitz/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin fa-2x"
    weight = 3
    url = "https://linkedin.com/in/niklas-arnitz-941250174/"

# Menu links
[[menu.main]]
    name = "Projects"
    weight = 1
    url  = "/projects/"

[[menu.main]]
    name = "Blog"
    weight = 2
    url = "/posts/"

[[menu.main]]
    name = "About"
    weight = 3
    url = "/about/"

[[menu.main]]
    name = "Privacy"
    weight = 4
    url = "/privacy/"

[[menu.main]]
    name = "Terms and Conditions"
    weight = 5
    url = "/terms-and-conditions/"

[[menu.main]]
    name = "Legal Disclosure"
    weight = 6
    url = "/legal-disclosure/"
